import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
// Read the actual shipped catalog data (as generated by importer/src/scrapeCatalog.js
// + importer/src/seed/applySeed.js) so these tests exercise the real, deployed
// requirement data — not a hand-copied stand-in that could drift out of sync.
const PROGRAMS_PATH = path.resolve(__dirname, "../../../public/data/programs.json");

let cachedPrograms = null;

function loadPrograms() {
  if (!cachedPrograms) {
    const raw = fs.readFileSync(PROGRAMS_PATH, "utf-8");
    cachedPrograms = JSON.parse(raw).programs;
  }
  return cachedPrograms;
}

export function findProgram({ name, degreeType }) {
  const program = loadPrograms().find((p) => p.name === name && p.degreeType === degreeType);
  if (!program) {
    throw new Error(
      `Fixture program not found: ${name} (${degreeType}). Did programs.json change shape, or does it need regenerating (npm run scrape && npm run seed:cs in /importer)?`
    );
  }
  return program;
}
